name: Release Drafter

on:
  push:
    types: [ closed ]
    branches: 
      - 'main' 
      - 'release/**'

  pull_request:
    types: [ closed ]
    branches: 
      - 'main' 
      - 'release/**'


jobs:
  update_release_draft:
    if: (github.event.pull_request.merged == true || github.event.push.merged == true) && (github.base_ref == 'main' || github.base_ref == 'release/**') 
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
