name: Release Drafter
on:
  push:
    branches:
      - 'main'
      - 'release/**'
jobs:
  update_release_draft:
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
